version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - mysqldb
        volumes:
            - ../ig-back:/var/www/symfony
            - ./site.conf:/etc/nginx/conf.d/default.conf/
        links:
            - php
            - mysqldb
    php:
        build:
            context: .
            dockerfile: Dockerfile 
        depends_on:
            - mysqldb
        volumes:
            - ../ig-back:/var/www/symfony
        links:
            - mysqldb
    mysqldb:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password 
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ig_db_test
            - MYSQL_USER=ig_project
            - MYSQL_PASSWORD=root
        ports:
            - "3308:3306" 
    elm: 
        build:
            context: ../ig-front
            dockerfile: Dockerfile 
        ports: 
          - "8001:80"



