version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - mysqldb
        volumes:
            - ./php:/php
            - ./site.conf:/etc/nginx/conf.d/default.conf/
        links:
            - php
            - mysqldb
    php:
        build:
            context: .
            dockerfile: Dockerfile 
        depends_on:
            - mysqldb
        volumes:
            - ./php:/php
        links:
            - mysqldb
    mysqldb:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password 
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ig_db_test
            - MYSQL_USER=ig_project
            - MYSQL_PASSWORD=root
        ports:
            - "3308:3306" 
    elm: 
        #image: wunsh/alpine-elm:latest
        build:
            context: /home/oussama/Documents/aio-group6-proj01/ig-front
            dockerfile: Dockerfile 
        ports: 
            - "8001:8001"
        #volumes: 
         #   - /home/oussama/Documents/aio-group6-proj01/ig-front/src/:/home/oussama/Documents/aio-group6-proj01/ig-front/src/
        #command: elm reactor


