name: elm-php CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
    - name: chekout and test
    - uses: actions/checkout@v2     
    - name: Set up elm 0.19.1 
      uses: actions/setup-elm@v1 
      with:
        elm-version: 0.19.1
         
    - name: Install dependencies
      run: |
        apm install linter,
        apm install language-elm,
        apm install linter-elm-make.
        
    - name: Lint with elm-lint
      run: |
        elm-lint file path .... 
    - name: Test with elm-test
      run: |
        elm file exec...
      env:
        CI: true
        
        
        
        
